service: next-boilerplate-app

custom:
  serverless-nextjs:
    customHandler: ./entry.js

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  memorySize: 512
  versionFunctions: false
  environment:
    LAMBDA: true

plugins:
  - serverless-nextjs-plugin

package:
  exclude:
    - ./**