service: next-boilerplate-app

stage: dev
region: eu-west-1

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  versionFunctions: false
  environment:
    LAMBDA: true

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    routes:
      - src: post
        path: post/{title}
        request:
          parameters:
            paths:
              title: ''
    customHandler: ./entry.js

package:
  exclude:
    - ./**
